import { BookOpen, CheckSquare, FileText, FolderOpen, LayoutDashboard, LogOut, Menu, Moon, Plus, Search, Sparkles, Sun, Target, X } from 'lucide-react'
import { FormEvent, useEffect, useState } from 'react'
import { NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import { api, ApiError, type Note, type Resource, type Revision, type Subject, type Task, type User, signIn } from './api'

const nav = [{ label: 'Dashboard', to: '/', icon: LayoutDashboard }, { label: 'Subjects', to: '/subjects', icon: BookOpen }, { label: 'Notes', to: '/notes', icon: FileText }, { label: 'Tasks', to: '/tasks', icon: CheckSquare }, { label: 'Resources', to: '/resources', icon: FolderOpen }, { label: 'Revision', to: '/revision', icon: Target }, { label: 'Progress', to: '/progress', icon: Sparkles }]
type Data = { user: User; subjects: Subject[]; notes: Note[]; tasks: Task[]; resources: Resource[]; revisions: Revision[] }

function App() {
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState(''), [dark, setDark] = useState(localStorage.getItem('studynest_theme') === 'dark'), [mobile, setMobile] = useState(false)
  const navigate = useNavigate()
  const load = async () => {
    try { const [user, subjects, notes, tasks, resources, revisions] = await Promise.all([api<User>('/auth/me'), api<Subject[]>('/subjects'), api<Note[]>('/notes'), api<Task[]>('/tasks'), api<Resource[]>('/resources'), api<Revision[]>('/revisions')]); setData({ user, subjects, notes, tasks, resources, revisions }); setError('') }
    catch (e) { localStorage.removeItem('studynest_token'); setData(null); if (e instanceof ApiError) setError(e.message) }
  }
  useEffect(() => { if (localStorage.getItem('studynest_token')) void load() }, [])
  useEffect(() => { localStorage.setItem('studynest_theme', dark ? 'dark' : 'light') }, [dark])
  if (!data) return <Auth error={error} onSuccess={load}/>
  const logout = () => { localStorage.removeItem('studynest_token'); setData(null); navigate('/') }
  return <div className={dark ? 'app dark' : 'app'}><aside className={mobile ? 'sidebar open' : 'sidebar'}><div className="brand"><span className="brand-mark"><BookOpen size={18}/></span>Study<span>Nest</span><button className="icon-button mobile-close" onClick={() => setMobile(false)}><X size={18}/></button></div><div className="workspace-label">WORKSPACE</div><nav>{nav.map(({ label, to, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} onClick={() => setMobile(false)} className={({isActive}) => isActive ? 'nav-link active' : 'nav-link'}><Icon size={18}/>{label}</NavLink>)}</nav><div className="sidebar-bottom"><button className="nav-link" onClick={logout}><LogOut size={18}/>Sign out</button><div className="profile"><div className="avatar">{initials(data.user.full_name)}</div><div><strong>{data.user.full_name}</strong><small>{data.user.course}</small></div></div></div></aside>{mobile && <div className="scrim" onClick={() => setMobile(false)}/>}<main className="main"><header className="topbar"><button className="icon-button menu-button" onClick={() => setMobile(true)}><Menu size={21}/></button><div className="crumb"><span>Workspace</span></div><div className="top-actions"><button className="theme-button" aria-label="Toggle theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={17}/> : <Moon size={17}/>}</button><div className="top-avatar">{initials(data.user.full_name)}</div></div></header><div className="content"><Routes><Route path="/" element={<Dashboard data={data}/>} /><Route path="/subjects" element={<SubjectsPage data={data} reload={load}/>} /><Route path="/notes" element={<NotesPage data={data} reload={load}/>} /><Route path="/tasks" element={<TasksPage data={data} reload={load}/>} /><Route path="/resources" element={<ResourcesPage data={data} reload={load}/>} /><Route path="/revision" element={<RevisionPage data={data} reload={load}/>} /><Route path="/progress" element={<ProgressPage data={data}/>} /><Route path="*" element={<Dashboard data={data}/>} /></Routes></div></main></div>
}

function Auth({ error, onSuccess }: { error: string; onSuccess: () => Promise<void> }) {
  const [mode, setMode] = useState<'login' | 'register'>('login'), [message, setMessage] = useState(error), [busy, setBusy] = useState(false)
  useEffect(() => setMessage(error), [error])
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { if (mode === 'login') await signIn(String(form.get('email')), String(form.get('password'))); else { await api('/auth/register', { method: 'POST', body: JSON.stringify({ full_name: form.get('full_name'), email: form.get('email'), password: form.get('password'), college: form.get('college'), course: form.get('course'), semester: Number(form.get('semester')) }) }); await signIn(String(form.get('email')), String(form.get('password'))) }; await onSuccess() } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to continue.') } finally { setBusy(false) } }
  return <main className="auth-page"><section className="auth-card"><div className="brand"><span className="brand-mark"><BookOpen size={18}/></span>Study<span>Nest</span></div><h1>{mode === 'login' ? 'Welcome back' : 'Create your workspace'}</h1><p>{mode === 'login' ? 'Sign in to continue planning your study time.' : 'Start organizing your courses, tasks and notes.'}</p><form onSubmit={submit} className="entity-form">{mode === 'register' && <><label>Full name<input required name="full_name" minLength={2}/></label><label>College / university<input required name="college" minLength={2}/></label><label>Course<input required name="course" minLength={2}/></label><label>Semester<input required name="semester" type="number" min="1" max="12" defaultValue="1"/></label></>}<label>Email<input required name="email" type="email" defaultValue={mode === 'login' ? 'student@studynest.edu' : ''}/></label><label>Password<input required name="password" type="password" minLength={8} defaultValue={mode === 'login' ? 'Student@123' : ''}/></label>{message && <p className="form-error">{message}</p>}<button className="button" disabled={busy}>{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form><button className="link-button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setMessage('') }}>{mode === 'login' ? 'Need an account? Register' : 'Already have an account? Sign in'}</button><small>Demo: student@studynest.edu / Student@123</small></section></main>
}

function PageHeader({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) { return <div className="page-header"><div><div className="eyebrow">STUDYNEST</div><h1>{title}</h1><p>{text}</p></div>{action}</div> }
function Dashboard({ data }: { data: Data }) { const done = data.tasks.filter(x => x.status === 'Completed').length; return <><PageHeader title={`Good day, ${data.user.full_name.split(' ')[0]}`} text="Here is the live view of your study workspace."/><div className="stats-grid"><Stat icon={<BookOpen/>} label="Subjects" value={data.subjects.length}/><Stat icon={<FileText/>} label="Notes" value={data.notes.length}/><Stat icon={<CheckSquare/>} label="Pending tasks" value={data.tasks.length - done}/><Stat icon={<Target/>} label="Completed" value={done}/></div><section className="panel"><div className="panel-heading"><div><h2>Upcoming tasks</h2><p>Keep moving through your plan.</p></div></div>{data.tasks.length ? data.tasks.slice(0, 5).map(task => <TaskRow key={task.id} task={task} subjects={data.subjects}/>) : <Empty text="Create a task to plan your next study session."/>}</section></> }
function Stat({ icon, label, value }: { icon: React.ReactNode; label: string; value: number }) { return <div className="stat-card"><div className="stat-icon indigo">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>Live workspace total</small></div></div> }

function SubjectsPage({ data, reload }: { data: Data; reload: () => Promise<void> }) { const [query, setQuery] = useState(''), [editing, setEditing] = useState<Subject | 'new' | null>(null); const subjects = data.subjects.filter(x => `${x.name} ${x.code}`.toLowerCase().includes(query.toLowerCase())); return <><PageHeader title="Subjects" text="Keep every course and its study material easy to find." action={<button className="button" onClick={() => setEditing('new')}><Plus size={17}/>Add subject</button>}/><SearchInput value={query} setValue={setQuery} label="Search subjects"/><div className="subject-grid large">{subjects.map(x => <article className="subject-card" key={x.id}><span className="subject-code">{x.code}</span><h3>{x.name}</h3><p>{x.description || 'No description yet.'}</p><div className="subject-meta"><span>{x.notes_count} notes</span><span>{x.tasks_count} tasks</span></div><div className="progress"><i style={{width: `${x.progress}%`}}/></div><Actions edit={() => setEditing(x)} remove={() => remove(`/subjects/${x.id}`, reload)}/></article>)}</div>{!subjects.length && <Empty text="No subjects yet. Add your first course."/>}{editing && <SubjectForm item={editing === 'new' ? undefined : editing} close={() => setEditing(null)} reload={reload}/>}</> }
function NotesPage({ data, reload }: { data: Data; reload: () => Promise<void> }) { const [query, setQuery] = useState(''), [editing, setEditing] = useState<Note | 'new' | null>(null); const notes = data.notes.filter(x => `${x.title} ${x.content} ${x.tags.join(' ')}`.toLowerCase().includes(query.toLowerCase())); return <><PageHeader title="Notes" text="Write, search and revisit your study material." action={<button className="button" disabled={!data.subjects.length} onClick={() => setEditing('new')}><Plus size={17}/>New note</button>}/><SearchInput value={query} setValue={setQuery} label="Search notes"/>{!data.subjects.length && <p className="form-error">Create a subject before adding notes.</p>}<div className="notes-grid">{notes.map(x => <article className="note-card" key={x.id}><div className="note-card-top"><span className="note-subject">{subjectName(data.subjects, x.subject_id)}</span><button className={x.favorite ? 'favorite selected' : 'favorite'} onClick={() => update(`/notes/${x.id}`, {...x, favorite: !x.favorite}, reload)}>★</button></div><h3>{x.title}</h3><p>{x.content || 'No content yet.'}</p><div className="tag-row">{x.tags.map(tag => <span className="tag" key={tag}>{tag}</span>)}</div><div className="note-footer"><span>Updated {new Date(x.updated_at).toLocaleDateString()}</span><Actions edit={() => setEditing(x)} remove={() => remove(`/notes/${x.id}`, reload)}/></div></article>)}</div>{!notes.length && <Empty text="No notes match this search."/>}{editing && <NoteForm subjects={data.subjects} item={editing === 'new' ? undefined : editing} close={() => setEditing(null)} reload={reload}/>}</> }
function TasksPage({ data, reload }: { data: Data; reload: () => Promise<void> }) { const [editing, setEditing] = useState<Task | 'new' | null>(null); return <><PageHeader title="Tasks" text="Turn your study intentions into achievable next steps." action={<button className="button" onClick={() => setEditing('new')}><Plus size={17}/>New task</button>}/><section className="panel">{data.tasks.length ? data.tasks.map(x => <TaskRow key={x.id} task={x} subjects={data.subjects} toggle={() => update(`/tasks/${x.id}`, {...x, status: x.status === 'Completed' ? 'Pending' : 'Completed'}, reload)} edit={() => setEditing(x)} remove={() => remove(`/tasks/${x.id}`, reload)}/>) : <Empty text="No tasks yet. Add one to make a plan."/>}</section>{editing && <TaskForm subjects={data.subjects} item={editing === 'new' ? undefined : editing} close={() => setEditing(null)} reload={reload}/>}</> }
function TaskRow({ task, subjects, toggle, edit, remove: del }: { task: Task; subjects: Subject[]; toggle?: () => void; edit?: () => void; remove?: () => void }) { return <div className={task.status === 'Completed' ? 'task-row done' : 'task-row'}><button className="check" onClick={toggle} aria-label="Toggle task">{task.status === 'Completed' && '✓'}</button><div className="task-copy"><strong>{task.title}</strong><span>{subjectName(subjects, task.subject_id)} · {task.due_date ? new Date(task.due_date).toLocaleDateString() : 'No due date'}</span></div><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span>{edit && del && <Actions edit={edit} remove={del}/>}</div> }
function ResourcesPage({ data, reload }: { data: Data; reload: () => Promise<void> }) { const [editing, setEditing] = useState<Resource | 'new' | null>(null); return <><PageHeader title="Resources" text="Keep useful links, videos and references close by." action={<button className="button" onClick={() => setEditing('new')}><Plus size={17}/>Add resource</button>}/><div className="resource-list">{data.resources.map(x => <div className="resource-row" key={x.id}><div className="resource-icon r0"><FolderOpen size={19}/></div><div><strong>{x.title}</strong><span>{subjectName(data.subjects, x.subject_id)} · {x.resource_type}</span></div><a href={x.url} target="_blank" rel="noreferrer">Open resource ↗</a><Actions edit={() => setEditing(x)} remove={() => remove(`/resources/${x.id}`, reload)}/></div>)}</div>{!data.resources.length && <Empty text="Save a helpful link, video or document."/>}{editing && <ResourceForm subjects={data.subjects} item={editing === 'new' ? undefined : editing} close={() => setEditing(null)} reload={reload}/>}</> }
function RevisionPage({ data, reload }: { data: Data; reload: () => Promise<void> }) { const [editing, setEditing] = useState<Revision | 'new' | null>(null); return <><PageHeader title="Revision" text="Plan what to revisit and track your confidence." action={<button className="button" onClick={() => setEditing('new')}><Plus size={17}/>Add topic</button>}/><section className="panel">{data.revisions.map(x => <div className="revision-row" key={x.id}><div className="revision-dot"/><div><strong>{x.topic}</strong><span>{subjectName(data.subjects, x.subject_id)}</span></div><span className={`revision-status ${x.status.toLowerCase().replace(' ', '-')}`}>{x.status}</span><Actions edit={() => setEditing(x)} remove={() => remove(`/revisions/${x.id}`, reload)}/></div>)}{!data.revisions.length && <Empty text="Add topics that deserve a second look."/>}</section>{editing && <RevisionForm subjects={data.subjects} item={editing === 'new' ? undefined : editing} close={() => setEditing(null)} reload={reload}/>}</> }
function ProgressPage({ data }: { data: Data }) { const done = data.tasks.filter(x => x.status === 'Completed').length; return <><PageHeader title="Progress" text="A clear view of the work you are putting in."/><div className="stats-grid"><Stat icon={<BookOpen/>} label="Subjects" value={data.subjects.length}/><Stat icon={<FileText/>} label="Notes created" value={data.notes.length}/><Stat icon={<CheckSquare/>} label="Tasks completed" value={done}/><Stat icon={<Target/>} label="Topics mastered" value={data.revisions.filter(x => x.status === 'Mastered').length}/></div></> }

function SearchInput({ value, setValue, label }: { value: string; setValue: (x: string) => void; label: string }) { return <label className="search page-search"><Search size={17}/><input value={value} onChange={e => setValue(e.target.value)} placeholder={label}/></label> }
function Actions({ edit, remove: del }: { edit: () => void; remove: () => void }) { return <span className="record-actions"><button onClick={edit}>Edit</button><button onClick={del}>Delete</button></span> }
function Empty({ text }: { text: string }) { return <div className="empty-mini"><BookOpen size={22}/><span>{text}</span></div> }
const initials = (name: string) => name.split(' ').map(x => x[0]).join('').slice(0, 2).toUpperCase()
const subjectName = (items: Subject[], id: string | null) => items.find(x => x.id === id)?.name || 'General'
async function update(path: string, body: unknown, reload: () => Promise<void>) { try { await api(path, { method: 'PUT', body: JSON.stringify(body) }); await reload() } catch (e) { alert(e instanceof Error ? e.message : 'Unable to save.') } }
async function remove(path: string, reload: () => Promise<void>) { if (!confirm('Delete this item? This cannot be undone.')) return; try { await api(path, { method: 'DELETE' }); await reload() } catch (e) { alert(e instanceof Error ? e.message : 'Unable to delete.') } }
function Modal({ title, close, children }: { title: string; close: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" onMouseDown={close}><section className="modal" onMouseDown={e => e.stopPropagation()}><button className="modal-close" onClick={close}>×</button><h2>{title}</h2>{children}</section></div> }
function FormShell({ title, close, onSubmit, children }: { title: string; close: () => void; onSubmit: (f: FormData) => Promise<void>; children: React.ReactNode }) { const [message, setMessage] = useState(''); return <Modal title={title} close={close}><form className="entity-form" onSubmit={async e => { e.preventDefault(); try { await onSubmit(new FormData(e.currentTarget)); close() } catch (err) { setMessage(err instanceof Error ? err.message : 'Unable to save.') } }}>{children}{message && <p className="form-error">{message}</p>}<button className="button">Save changes</button></form></Modal> }
const subjectOptions = (subjects: Subject[], value?: string | null) => <label>Subject<select name="subject_id" defaultValue={value || ''}><option value="">General / none</option>{subjects.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
function SubjectForm({ item, close, reload }: { item?: Subject; close: () => void; reload: () => Promise<void> }) { return <FormShell title={item ? 'Edit subject' : 'Add subject'} close={close} onSubmit={async f => { await api(item ? `/subjects/${item.id}` : '/subjects', { method: item ? 'PUT' : 'POST', body: JSON.stringify({ name: f.get('name'), code: f.get('code'), description: f.get('description'), semester: Number(f.get('semester')) }) }); await reload() }}><label>Name<input required name="name" defaultValue={item?.name}/></label><label>Code<input required name="code" defaultValue={item?.code}/></label><label>Semester<input required type="number" min="1" max="12" name="semester" defaultValue={item?.semester || 1}/></label><label>Description<textarea name="description" defaultValue={item?.description}/></label></FormShell> }
function NoteForm({ subjects, item, close, reload }: { subjects: Subject[]; item?: Note; close: () => void; reload: () => Promise<void> }) { return <FormShell title={item ? 'Edit note' : 'New note'} close={close} onSubmit={async f => { await api(item ? `/notes/${item.id}` : '/notes', { method: item ? 'PUT' : 'POST', body: JSON.stringify({ title: f.get('title'), content: f.get('content'), subject_id: f.get('subject_id'), tags: String(f.get('tags')).split(',').map(x => x.trim()).filter(Boolean), favorite: item?.favorite || false, archived: false }) }); await reload() }}><label>Title<input required name="title" defaultValue={item?.title}/></label>{subjectOptions(subjects, item?.subject_id)}<label>Tags (comma separated)<input name="tags" defaultValue={item?.tags.join(', ')}/></label><label>Content<textarea name="content" defaultValue={item?.content}/></label></FormShell> }
function TaskForm({ subjects, item, close, reload }: { subjects: Subject[]; item?: Task; close: () => void; reload: () => Promise<void> }) { return <FormShell title={item ? 'Edit task' : 'New task'} close={close} onSubmit={async f => { await api(item ? `/tasks/${item.id}` : '/tasks', { method: item ? 'PUT' : 'POST', body: JSON.stringify({ title: f.get('title'), description: f.get('description'), subject_id: f.get('subject_id') || null, due_date: f.get('due_date') ? new Date(String(f.get('due_date'))).toISOString() : null, priority: f.get('priority'), task_type: 'Study task', status: f.get('status') }) }); await reload() }}><label>Title<input required name="title" defaultValue={item?.title}/></label>{subjectOptions(subjects, item?.subject_id)}<label>Due date<input name="due_date" type="date" defaultValue={item?.due_date?.slice(0, 10)}/></label><label>Priority<select name="priority" defaultValue={item?.priority || 'Medium'}><option>Low</option><option>Medium</option><option>High</option></select></label><label>Status<select name="status" defaultValue={item?.status || 'Pending'}><option>Pending</option><option>In Progress</option><option>Completed</option></select></label><label>Description<textarea name="description" defaultValue={item?.description}/></label></FormShell> }
function ResourceForm({ subjects, item, close, reload }: { subjects: Subject[]; item?: Resource; close: () => void; reload: () => Promise<void> }) { return <FormShell title={item ? 'Edit resource' : 'Add resource'} close={close} onSubmit={async f => { await api(item ? `/resources/${item.id}` : '/resources', { method: item ? 'PUT' : 'POST', body: JSON.stringify({ title: f.get('title'), url: f.get('url'), subject_id: f.get('subject_id') || null, resource_type: f.get('resource_type'), description: f.get('description') }) }); await reload() }}><label>Title<input required name="title" defaultValue={item?.title}/></label><label>URL<input required type="url" name="url" defaultValue={item?.url}/></label>{subjectOptions(subjects, item?.subject_id)}<label>Type<select name="resource_type" defaultValue={item?.resource_type || 'Website'}><option>Website</option><option>Video</option><option>Article</option><option>PDF</option></select></label><label>Description<textarea name="description" defaultValue={item?.description}/></label></FormShell> }
function RevisionForm({ subjects, item, close, reload }: { subjects: Subject[]; item?: Revision; close: () => void; reload: () => Promise<void> }) { return <FormShell title={item ? 'Edit revision topic' : 'Add revision topic'} close={close} onSubmit={async f => { await api(item ? `/revisions/${item.id}` : '/revisions', { method: item ? 'PUT' : 'POST', body: JSON.stringify({ topic: f.get('topic'), subject_id: f.get('subject_id') || null, status: f.get('status'), next_review_at: null }) }); await reload() }}><label>Topic<input required name="topic" defaultValue={item?.topic}/></label>{subjectOptions(subjects, item?.subject_id)}<label>Status<select name="status" defaultValue={item?.status || 'Needs Revision'}><option>Needs Revision</option><option>Reviewed</option><option>Mastered</option></select></label></FormShell> }
export default App
